### ISSUE TITLE
你好，关于class="mb-2 mt-4"中，1表示8rpx如何修改？

### ISSUE THREAD

**Issue by betteroneday** [MellowCo/uni-vue3-starter#2]
你好，该项目里的unocss
mb-2表示margin-bottom: 16rpx
mt-4表示是margin-top: 32rpx
1份表示8rpx，我应该如何修改，或者说我应该如何处理这种对应关系，因为在写代码时换算是个麻烦的事情...
谢谢

**Comment by MellowCo** [comment]
8rpx 是很标准的换算啊

你可以自己定义unocss规则覆盖

**Comment by MellowCo** [comment]
rules: [
    [/^m-(\d*)$/, ([, d]) => ({ margin: `${d}rpx` })],
  ],

**Comment by betteroneday** [comment]
> 

感谢，参考这个，已解决
